### ISSUE TITLE
Header: The phone number should use the 'EurostileLT Demi' font

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Ironcat-Tyres#13]
Eurostile LT is not the equivalent of Eurostile Regular, it has a squarer outline and is larger.

A demi-bold font weight value would be closer to 600 than 700. However, this is not guaranteed to be processed by all browsers. I would suggest using font that is already in demi-bold.

**Comment by ramoncebudigital** [comment]
Since the EurostileLT Demi font is blacklisted by the generator, Stan confirmed that he is ok with the current font.
