### ISSUE TITLE
Header: The phone number is too large on the iTouch, also affecting its layout with regards to the opening hours and address when viewed in landscape mode

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Ironcat-Tyres#65]
This is also an issue on the iPad, Samsung Tab 3 and, Samsung S3

**Comment by bernardtitan** [comment]
This remains an issue on the iTouch

**Comment by ramoncebudigital** [comment]
please provide screenshot. tnx

**Comment by bernardtitan** [comment]
![image](https://cloud.githubusercontent.com/assets/11186359/6635594/d35afa34-c9a2-11e4-9627-31207044f8fc.jpg)

**Comment by ramoncebudigital** [comment]
This is okay on my side. please refresh hard the browser or try to clear cache. tnx

**Comment by bernardtitan** [comment]
Did both, there is no change
